<link rel="stylesheet" href="<?= config('app.view_static') ?>/static/global/plugins/datatables/datatables.min.css"/>
<link rel="stylesheet"
      href="<?= config('app.view_static') ?>/static/global/plugins/datatables/plugins/bootstrap/datatables.bootstrap.css"/>
<script src="<?= config('app.view_static') ?>/static/global/plugins/datatables/datatables.min.js"
        type="text/javascript"></script>
<script src="<?= config('app.view_static') ?>/static/global/plugins/datatables/plugins/bootstrap/datatables.bootstrap.js"
        type="text/javascript"></script>
<script src="<?= config('app.view_static') ?>/static/global/scripts/hs-datatable.js" type="text/javascript"></script>
<link href="<?= config('app.view_static') ?>/static/global/plugins/bootstrap-datepicker/css/bootstrap-datepicker3.min.css"
      rel="stylesheet" type="text/css"/>
<script src="<?= config('app.view_static') ?>/static/global/plugins/bootstrap-datepicker/js/bootstrap-datepicker.js"
        type="text/javascript"></script>
<script src="<?= config('app.view_static') ?>/static/global/plugins/bootstrap-datepicker/locales/bootstrap-datepicker.vi.min.js"
        type="text/javascript"></script>
<link href="<?= config('app.view_static') ?>/static/global/plugins/select2/css/select2.min.css" rel="stylesheet"
      type="text/css"/>
<link href="<?= config('app.view_static') ?>/static/global/plugins/select2/css/select2-bootstrap.min.css"
      rel="stylesheet" type="text/css"/>
<script src="<?= config('app.view_static') ?>/static/global/plugins/select2/js/select2.full.min.js"
        type="text/javascript"></script>
<script src="<?= config('app.view_static') ?>/static/pages/scripts/load-init.js?v=<?= time() ?>"
        type="text/javascript"></script>
<script src="<?=config('app.view_static')?>/static/pages/scripts/handle-form.js?v=<?=time()?>" type="text/javascript"></script>
<script src="<?= config('app.view_static') ?>/static/pages/scripts/survey/question.js?v=<?= time() ?>"
        type="text/javascript"></script>
<style>
    .lbl-info {
        font-weight: 600;
        margin-left: 5px;
        font-size: 20px;
    }

    .lbl-info2 {
        font-weight: 600;
        margin-left: 5px;
        font-size: 14px;
    }

    .fw400 {
        font-weight: 400 !important;
    }

    span.label {
        font-size: 14px !important
    }
</style>
<div class="page-content-wrapper">
    <div class="page-content">
        <h1 class="page-title font-dark bold uppercase"><i class="fa <?= $icon ?>"></i> <?= $title ?></h1>
        <div class="row">
            <div class="col-md-12">
                <div class="portlet light bordered">
                    <div class="portlet-body form filter">

                        <div class="form-body">
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label class="control-label">Nhóm câu hỏi</label>
                                        <select name="question_group_search" id="question_group_search"
                                                class="form-filter form-control">
                                            <option value="0">Chọn nhóm câu hỏi</option>
                                            <?php foreach ($question_group as $v) : ?>
                                                <option value="<?= $v['id'] ?>"><?= sprintf('%s-%s_%s', $v['customer_group'], $v['customer'], $v['name']) ?></option>
                                            <?php endforeach; ?>
                                        </select>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="form-actions right">
                            <?= allow_acl('list', App\Controllers\survey\QuestionController::class) ? block('button-search') : '' ?>
                            <?= allow_acl('update', App\Controllers\survey\QuestionController::class) ? block('button-add') : '' ?>
                        </div>

                    </div>
                </div>
            </div>
        </div>

        <div class="modal fade" id="modalAdd" role="basic" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
                        <h4 class="modal-title" id="titleAdd">Thêm mới Câu hỏi</h4>
                    </div>
                    <div class="modal-body">
                        <form id="add-form">
                            <input type="hidden" id="id" name="id">
                            <input type="text" id="answer-delete" value=" "  hidden/>
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label class="control-label">Khách hàng(*)</label>
                                        <select name="customer_id" id="customer_field" class="form-control">
                                            <option value="0">Chọn Khách hàng</option>
                                            <?php foreach ($customer_list as $v) : ?>
                                                <option value="<?= $v['id'] ?>"><?=$v['customer_group'].'-'.$v['name'] ?></option>
                                            <?php endforeach; ?>
                                        </select>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label class="control-label">Nhóm câu hỏi(*)</label>
                                        <select name="group_id" id="question_group_field" class="form-control"  style="width:100%">
                                            <option value="0">Chọn nhóm câu hỏi</option>

                                        </select>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-9">
                                    <div class="form-group">
                                        <label class="control-label">Câu hỏi(*)</label>
                                        <input type="text" class="form-control" name="content"  placeholder="Nhập câu hỏi">

                                    </div>
                                </div>
                                <div class="col-md-3">
                                    <div class="form-group">
                                        <label class="control-label">Loại câu hỏi(*)</label>
                                        <select name="type" id="type_field"
                                                class="form-control"  style="width:100%">
                                            <option value="0">Chọn loại</option>
                                            <option value="1">Radio button</option>
                                            <option value="2">Dropdown</option>
                                            <option value="3">Checkbox</option>
                                            <option value="4">Text</option>
                                        </select>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label class="control-label">Mô tả(*)</label>
                                        <textarea name="description" class="form-control" cols="8"></textarea>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                    <div class="col-md-12">
                                        <label class="control-label" >Câu trả lời(*)</label>
                                        <div id="anwsers" name="anwsers">

                                        </div>
                                        <div >
                                            <a href="javascript:;" id="add-anwser" class="btn green btn-outline">
                                                <i class="fa fa-plus"></i> <span>Thêm câu trả lời</span>
                                            </a>
                                        </div>
                                    </div>
                            </div>
                            
                            <div class="row" style="margin-top: 20px">
                                <div class="col-md-12">
                                    <label class="mt-checkbox mt-checkbox-outline">
                                        Hoạt động: Tắt/Mở
                                        <input type="checkbox" name="status" id="status" value="1" checked>
                                        <span></span>
                                    </label>
                                </div>
                            </div>
                        </form>
                    </div>

                    <div class="modal-footer">
                        <button type="button" class="btn dark btn-outline" data-dismiss="modal">Đóng</button>
                        <button type="button" id="btn-add" class="btn green">Đồng ý</button>
                    </div>

                </div>
            </div>
        </div>


        <div class="row clearfix">
            <div class="col-md-12">
                <div class="table-container">
                    <table class="table table-striped table-bordered table-hover table-checkable"
                           id="device-table"
                           data-url="<?= url('config/question/list') ?>">
                        <thead>
                        <tr role="row" style="background-color: #5E738B">
                            <th width="2%" class="th-header">STT&nbsp;#</th>
                            <th width="8%" class="th-header">Chức năng</th>
                            <th width="15%" class="th-header">Khách hàng</th>
                            <th width="10%" class="th-header">Nhóm câu hỏi</th>
                            <th width="20%" class="th-header">Câu hỏi</th>
                            <th width="25%" class="th-header">Mô tả</th>
                            <th width="8%" class="th-header">Loại câu hỏi</th>
                            <th width="5%" class="th-header">Trạng thái</th>
                            <th width="10%" class="th-header">Người cập nhật</th>
                        </tr>
                        </thead>
                        <tbody></tbody>
                    </table>
                </div>
            </div>
        </div>

    </div>
</div>

<template id="template-anwser">
    <div  name="anwser" style="display: flex;align-items: center;margin-bottom: 15px;">
        <div class="col-10" style="margin-bottom: 0px;width: 100%;padding-right: 10px">
            <input type="text" name="anwser" data-id="0"
                   class="form-filter form-control" placeholder="Nhập câu trả lời" required>
        </div>
        <div class="col-2">
            <a class="form-filter btn btn-danger delete-anwser" title="Xóa ?" name="delete-button" data-id="0" data-toggle="tooltip"><i class="fa fa-times"></i></a>
        </div>
    </div>
</template>

