<link rel="stylesheet" href="<?= config('app.view_static') ?>/static/global/plugins/datatables/datatables.min.css"/>
<link rel="stylesheet"
      href="<?= config('app.view_static') ?>/static/global/plugins/datatables/plugins/bootstrap/datatables.bootstrap.css"/>
<script src="<?= config('app.view_static') ?>/static/global/plugins/datatables/datatables.min.js"
        type="text/javascript"></script>
<script src="<?= config('app.view_static') ?>/static/global/plugins/datatables/plugins/bootstrap/datatables.bootstrap.js"
        type="text/javascript"></script>
<script src="<?= config('app.view_static') ?>/static/global/scripts/hs-datatable.js" type="text/javascript"></script>
<link href="<?= config('app.view_static') ?>/static/global/plugins/bootstrap-datepicker/css/bootstrap-datepicker3.min.css"
      rel="stylesheet" type="text/css"/>
<script src="<?= config('app.view_static') ?>/static/global/plugins/bootstrap-datepicker/js/bootstrap-datepicker.js"
        type="text/javascript"></script>
<script src="<?= config('app.view_static') ?>/static/global/plugins/bootstrap-datepicker/locales/bootstrap-datepicker.vi.min.js"
        type="text/javascript"></script>
<link href="<?= config('app.view_static') ?>/static/global/plugins/select2/css/select2.min.css" rel="stylesheet"
      type="text/css"/>
<link href="<?= config('app.view_static') ?>/static/global/plugins/select2/css/select2-bootstrap.min.css"
      rel="stylesheet" type="text/css"/>
<script src="<?= config('app.view_static') ?>/static/global/plugins/select2/js/select2.full.min.js"
        type="text/javascript"></script>
<script src="<?= config('app.view_static') ?>/static/pages/scripts/load-init.js?v=<?= time() ?>"
        type="text/javascript"></script>
<script src="<?= config('app.view_static') ?>/static/pages/scripts/handle-form.js?v=<?= time() ?>"
        type="text/javascript"></script>
<script src="<?= config('app.view_static') ?>/static/pages/scripts/survey/question-collection.js?v=<?= time() ?>"
        type="text/javascript"></script>
<style>
    .delete-section{
        background-image: url(<?= config('app.view_static')."/static/global/img/portlet-remove-icon.png" ?>);
        background-repeat: no-repeat;
        width: 11px

    }
    .lbl-info {
        font-weight: 600;
        margin-left: 5px;
        font-size: 20px;
    }

    .lbl-info2 {
        font-weight: 600;
        margin-left: 5px;
        font-size: 14px;
    }

    .fw400 {
        font-weight: 400 !important;
    }

    span.label {
        font-size: 14px !important
    }
</style>
<div class="page-content-wrapper">
    <div class="page-content">
        <h1 class="page-title font-dark bold uppercase"><i class="fa <?= $icon ?>"></i> <?= $title ?></h1>
        <div class="row">
            <div class="col-md-12">
                <div class="portlet light bordered">
                    <div class="portlet-body form filter">

                        <div class="form-body">
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label class="control-label">Bộ câu hỏi</label>
                                        <select name="question_collection_search" id="question_collection_search"
                                                class="form-filter form-control select2">
                                            <option value="0">Chọn bộ câu hỏi</option>
                                            <?php foreach ($question_collection as $v) : ?>
                                                <option value="<?= $v['id'] ?>"><?= sprintf('%s-%s_%s', $v['customer_group'], $v['customer'], $v['name']) ?></option>
                                            <?php endforeach; ?>
                                        </select>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="form-actions right">
                            <?= allow_acl('list', App\Controllers\survey\QuestionCollectionController::class) ? block('button-search') : '' ?>
                            <?= allow_acl('update', App\Controllers\survey\QuestionCollectionController::class) ? block('button-add') : '' ?>
                        </div>

                    </div>
                </div>
            </div>
        </div>

<!--        copy form-->

<!--add-->
        <div class="modal fade" id="modalAdd" role="basic" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
                        <h4 class="modal-title" id="titleAdd">Thêm mới Bộ câu hỏi</h4>
                    </div>
                    <div class="modal-body">
                        <form id="add-form">
                            <input type="hidden" id="id" name="id">
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label class="control-label">Khách hàng(*)</label>
                                        <select name="customer_id" id="customer_field" class="form-control">
                                            <option value="0">Chọn Khách hàng</option>
                                            <?php foreach ($customer_list as $v) : ?>
                                                <option value="<?= $v['id'] ?>"><?= $v['customer_group'] . '-' . $v['name'] ?></option>
                                            <?php endforeach; ?>
                                        </select>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label class="control-label">Tên bộ câu hỏi(*)</label>
                                        <input type="text" class="form-control" name="name" placeholder="Nhập câu hỏi">

                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label class="control-label">Mô tả(*)</label>
                                        <textarea name="description" class="form-control" cols="8"></textarea>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-12">
                                    <label class="mt-checkbox mt-checkbox-outline">
                                        Hoạt động: Tắt/Mở
                                        <input type="checkbox" name="status" id="status" value="1" checked>
                                        <span></span>
                                    </label>
                                </div>
                            </div>
                        </form>
                    </div>

                    <div class="modal-footer">
                        <button type="button" class="btn dark btn-outline" data-dismiss="modal">Đóng</button>
                        <button type="button" id="btn-add" class="btn green">Đồng ý</button>
                    </div>

                </div>
            </div>
        </div>
        <!--modal create survey-->
        <div class="modal bs-modal-lg in" id="modalSurvey" role="basic" aria-hidden="true">
            <div class="modal-dialog modal-lg">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
                        <h4 class="modal-title" id="titleSurvey">Quản lý Bộ câu hỏi</h4>
                    </div>
                    <div class="modal-body">
                        <form id="survey-form">
                            <input type="hidden" name="id">
                            <input type="hidden" name="customer_id">
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label class="control-label">Khách hàng:</label>
                                        <span name="customer-name"></span>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label class="control-label">Tên:</label>
                                        <span name="name"></span>
                                    </div>
                                </div>
                            </div>
                            <div id="section-content">
                                <div class="section-content" name="section-content">

                                </div>
                                <a href="javascript:;" id="add-section" class="btn green btn-outline">
                                    <i class="fa fa-plus"></i> <span>Thêm section</span>
                                </a>
                            </div>

                        </form>
                    </div>

                    <div class="modal-footer">
                        <button type="button" class="btn dark btn-outline" data-dismiss="modal">Đóng</button>
                        <button type="button" id="btn-survey" class="btn green">Đồng ý</button>
                    </div>

                </div>
            </div>
        </div>


        <div class="row clearfix">
            <div class="col-md-12">
                <div class="table-container">
                    <table class="table table-striped table-bordered table-hover table-checkable"
                           id="device-table"
                           data-url="<?= url('config/question-collection/list') ?>">
                        <thead>
                        <tr role="row" style="background-color: #5E738B">
                            <th width="2%" class="th-header">STT&nbsp;#</th>
                            <th width="8%" class="th-header">Chức năng</th>
                            <th width="15%" class="th-header">Khách hàng</th>
                            <th width="10%" class="th-header">Bộ câu hỏi</th>
                            <th width="15%" class="th-header">Mô tả</th>
                            <th width="5%" class="th-header">Trạng thái</th>
                            <th width="10%" class="th-header">Người cập nhật</th>
                        </tr>
                        </thead>
                        <tbody></tbody>
                    </table>
                </div>
            </div>
        </div>

    </div>
</div>
<template id="section-template">
    <div class="portlet light bordered" name="section">
        <input name="section_sort" hidden>
        <input name="section_id" value="0" hidden>
        <div class="portlet-title">
            <div class="caption">
                <i class="icon-equalizer font-dark hide"></i>
                <span name="section-title" class="caption-subject font-dark bold uppercase"></span>
            </div>
            <div class="tools">
                <a href="" class="collapse" data-original-title="" title=""> </a>
                <a href="" class="delete-section"> </a>
            </div>
        </div>
        <div class="portlet-body">
            <div name="group-content" class="group-content">
            </div>
            <a href="javascript:;" class="btn green btn-outline add-question-group">
                <i class="fa fa-plus"></i> <span>Thêm nhóm câu hỏi</span>
            </a>

        </div>
    </div>

</template>
<template id="template-question-group">
        <div name="question-group"  style="border-bottom: 1px solid #eef1f5;margin-bottom: 10px">
            <input name="group_id" value="0" hidden>
            <input name="group_sort" value="0" hidden>
            <div class="row">
                <div class="col-md-10">
                    <div class="form-group" style="display: flex; justify-content: flex-start; align-items: center; gap: 8px">
                        <label class="control-label" style="white-space: nowrap">Nhóm câu hỏi: </label>
                        <select name="question_group_filed"  class="form-control question_group_filed">
                            <option value="0">Chọn nhóm câu hỏi</option>
                        </select>
                        <a href="javascript:;" class="btn btn-sm btn-circle red delete-question-group"
                        <i class="fa fa-times"></i> Xóa </a>
                    </div>
                </div>
                <div class="col-md-8" style="display: flex; justify-content: flex-end;align-items: center">

                </div>
            </div>
            <div style="margin-left: 40px; padding: 10px;padding-top: 0px">
                <label class="control-label">Câu hỏi và Trả lời:</label>
                <div name="question-content" class="question-content" style="padding: 10px">

                </div>
                    <a href="javascript:;" class="btn green btn-outline add-question">
                        <i class="fa fa-plus"></i> <span>Thêm câu hỏi</span>
                    </a>
            </div>

        </div>
</template>
<template id="template-question">
    <div name="question" style="margin-top: 10px;border-bottom: 1px solid #eef1f5;padding-bottom: 8px;">
        <input name="section_question_id" value="0" hidden>
        <input name="section_question_sort" hidden>
        <div class="row">
            <div class="col-md-1" style="padding: 0; display: flex; align-items: center; padding-left: 8px" name="question-number">

            </div>
            <div class="col-md-11">
                <div class="row">
                    <div class="col-md-8">
                        <div class="form-group">
                            <select name="question_field" class="form-control question_field">
                                <option value="0">Chọn câu hỏi</option>
                            </select>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <a href="javascript:;" class="btn btn-sm btn-circle red delete-question"
                        <i class="fa fa-times"></i> Xóa </a>
                    </div>
                </div>
            </div>
        </div>
        <div class="row" name="question-content-detail">

        </div>
    </div>
</template>
<template id="template-question-detail" >
    <div class="col-md-1">
    </div>
    <div class="col-md-11">
        <div class="row">
            <div class="col-md-8">
                <textarea disabled name="question-description" class="form-control"></textarea>
            </div>
            <div class="col-md-4">
                <div class="form-group">
                    <select name="question-type" class="form-control" disabled>
                        <option value="1">Radio button</option>
                        <option value="2">Dropdown</option>
                        <option value="3">Checkbox</option>
                        <option value="4">Text</option>
                    </select>
                </div>
            </div>
        </div>
        <div name="anwsers-content">
        </div>
    </div>
</template>
<template id="template-anwser">
    <div class="row" name="anwser" style="margin-top: 4px">
        <div class="col-md-8">
            <input  type="text" name="anwser-content" class="form-control" disabled>
        </div>
        <div class="col-md-4">
            <select name="section-forward" class="form-control">
                <option value="0">Chọn section đi tiếp</option>
                <option value="-1">Hoàn thành khảo sát</option>
            </select>
        </div>

    </div>

</template>

