<div class="form-group">
    <label class="control-label">Quận huyện</label>
    <select name="district_search" id="district_search" class="form-filter form-control select2">
        <option value="0">Chọn quận huyện</option>
        <?php foreach ($district as $v) : ?>
            <?=$selected=($get??0) && isset($_GET['district']) && $v['id']==$_GET['district']?'selected':''?>
            <option value="<?= $v['id'] ?>" <?=$selected?>><?= $v['name'] ?></option>
        <?php endforeach; ?>
    </select>
</div>