<div class="form-group">
    <label class="control-label">Trạng thái triển khai</label>
    <select name="status_search" id="status_search" class="form-filter form-control">
        <option value="0">Chọn trạng thái triển khai</option>
        <?php foreach ($status as $v) : ?>
            <option value="<?= $v['id'] ?>"><?= $v['name'] ?></option>
        <?php endforeach; ?>                                                
    </select>
</div>