<div class="form-group">
    <label class="control-label">Mô hình kinh doanh</label>
    <select name="business_model_search" id="business_model_search" class="form-filter form-control">
        <option value="0">Chọn mô hình kinh doanh</option>
        <?php foreach (config('info.business_model') as $v) : ?>
            <option value="<?= $v['id'] ?>"><?= $v['name'] ?></option>
        <?php endforeach; ?>
    </select>
</div>