<div class="form-group">
    <label class="control-label">Đơn vị triển khai</label>
    <?=($required??0)?'<span class="required"> * </span>':''?>
    <select name="implementation_unit" id="implementation_unit" class="form-control">
        <option value="">Chọn Đơn vị triển khai</option>
        <?php foreach (config('info.implementation_unit') as $v) : ?>
        <option value="<?=$v['id']?>"><?=$v['name']?></option>
        <?php endforeach; ?>
    </select>
</div>