<div class="form-group">
    <label class="control-label">Nguồn phát sinh</label>
    <select name="source_arising_search" id="source_arising_search" class="form-filter form-control">
        <option value="0">Chọn Nguồn phát sinh</option>
        <?php foreach (config('info.source_arising') as $v) : ?>
            <option value="<?= $v ?>"><?= $v ?></option>
        <?php endforeach; ?>
    </select>
</div>