<div class="form-group">
    <label class="control-label">Deadline so với hiện tại</label>
    <select name="deadline2_search" id="deadline2_search" class="form-filter form-control">
        <option value="0">Chọn Ngày hết hạn với hiện tại</option>
        <option value="<?=today().';'.today()?>">Hôm nay (<?=today()?>)</option>
        <option value="<?=today().';'.date('Y-m-d', strtotime('+ 2 day'))?>">Còn 2 ngày (Hôm nay đến <?=date('Y-m-d', strtotime('+ 2 day'))?>)</option>
        <option value="<?=today().';'.date('Y-m-d', strtotime('+ 5 day'))?>">Còn 5 ngày (Hôm nay đến <?=date('Y-m-d', strtotime('+ 5 day'))?>)</option>
        <option value="<?=today().';'.date('Y-m-d', strtotime('+ 10 day'))?>">Còn 10 ngày (Hôm nay đến <?=date('Y-m-d', strtotime('+ 10 day'))?>)</option>
        <option value="<?='2000-01-01;'.date('Y-m-d', strtotime('- 1 day'))?>">Quá hạn</option>
    </select>
</div>