<div class="form-group">
    <label class="control-label">Tỉnh thành</label>
    <select name="city_search" id="city_search" class="form-filter form-control select2">
        <option value="0">Chọn tỉnh thành</option>
        <?php foreach ($city as $v) : ?>
            <?=$selected=($get??0) && isset($_GET['city']) && $v['id']==$_GET['city']?'selected':''?>
            <option value="<?= $v['id'] ?>" <?=$selected?>><?= $v['name'] ?></option>
        <?php endforeach; ?>
    </select>
</div>