<?php if (allow_acl('sourceVerify', App\Controllers\CronController::class)) : ?>
    <?php if ($block??0) : ?>
    <div class="col-md-3">
        <div class="form-group">
            <a href="javascript:;" id="source_verify" class="btn yellow btn-block" data-style="zoom-in">
                <span class="ladda-label"><i class="fa fa-database"></i> <?=config('title.action.sourceVerify')?></span>
                <span class="ladda-spinner"></span>
            </a>   
        </div>
    </div>
    <?php else: ?>
    <a href="javascript:;" id="source_verify" class="btn yellow" data-style="zoom-in">
        <span class="ladda-label"><i class="fa fa-database"></i> <?=config('title.action.sourceVerify')?></span>
        <span class="ladda-spinner"></span>
    </a>    
    <?php endif; ?>
    <script>
    jQuery(document).ready(function () {
        $('#source_verify').click(function () {
            var l = Ladda.create(document.querySelector('#source_verify'));
            l.start();
            $.get(SUB_DOMAIN+'/cron/source-verify', function (d) {
                const store_success = parseInt(d.data.store.success);
                const store_count   = parseInt(d.data.store.count);
                const form_success  = parseInt(d.data.form.success);
                const form_count    = parseInt(d.data.form.count);
                
                swal(`STORE Xử lý thành công : ${store_success.toLocaleString('vi-VN')} , từ ${store_count.toLocaleString('vi-VN')} dữ liệu                
                    FORM Xử lý thành công : ${form_success.toLocaleString('vi-VN')} , từ ${form_count.toLocaleString('vi-VN')} dữ liệu`, {
                    icon: 'success'
                });

                l.stop();
            });
        });
    });    
    </script>
<?php endif; ?>