<?php if (allow_acl('zalopayCreatedAt', App\Controllers\CronController::class)) : ?>
    <?php if ($block??0) : ?>
    <div class="col-md-3">
        <div class="form-group">
            <a href="javascript:;" id="zalopay_created_at" class="btn btn-block" style="background-color:violet;color:white" data-style="zoom-in">
                <span class="ladda-label"><i class="fa fa-calendar"></i> <?=config('title.action.zalopayCreatedAt')?></span>
                <span class="ladda-spinner"></span>
            </a>   
        </div>
    </div>
    <?php else: ?>
    <a href="javascript:;" id="zalopay_created_at" class="btn" style="background-color:violet;color:white" data-style="zoom-in">
        <span class="ladda-label"><i class="fa fa-calendar"></i> <?=config('title.action.zalopayCreatedAt')?></span>
        <span class="ladda-spinner"></span>
    </a>       
    <?php endif; ?>
    <script>
    jQuery(document).ready(function () {
        $('#zalopay_created_at').click(function () {
            var l = Ladda.create(document.querySelector('#zalopay_created_at'));
            l.start();
            $.get(SUB_DOMAIN+'/cron/zalopay-created-at', function (d) {
                const merchant_success = parseInt(d.data.zalopay_merchant.success);
                const merchant_count   = parseInt(d.data.zalopay_merchant.count);
                const store_success    = parseInt(d.data.zalopay_store.success);
                const store_count      = parseInt(d.data.zalopay_store.count);
                
                swal(`ZLP Merchant Xử lý thành công : ${merchant_success.toLocaleString('vi-VN')} , từ ${merchant_count.toLocaleString('vi-VN')} dữ liệu                
                    ZLP Store Xử lý thành công : ${store_success.toLocaleString('vi-VN')} , từ ${store_count.toLocaleString('vi-VN')} dữ liệu`, {
                    icon: 'success'
                });

                l.stop();
            });
        });
    });    
    </script>
<?php endif; ?>