<?php if (allow_acl('latlgn', App\Controllers\CronController::class)) : ?>
    <?php if ($block??0) : ?>
    <div class="col-md-3">
        <div class="form-group">
            <a href="javascript:;" id="latlgn" class="btn btn-block" style="background-color:#561771;color:white" data-style="zoom-in">
                <span class="ladda-label"><i class="fa fa-map-marker"></i> <?=config('title.action.latlgn')?></span>
                <span class="ladda-spinner"></span>
            </a>
        </div>
    </div>
    <?php else: ?>
        <a href="javascript:;" id="latlgn" class="btn" style="background-color:#561771;color:white" data-style="zoom-in">
            <span class="ladda-label"><i class="fa fa-map-marker"></i> <?=config('title.action.latlgn')?></span>
            <span class="ladda-spinner"></span>
        </a>
    <?php endif; ?>
    <script>
    jQuery(document).ready(function () {
        $('#latlgn').click(function () {
            var l = Ladda.create(document.querySelector('#latlgn'));
            l.start();
            $.get(SUB_DOMAIN+'/cron/lat-lgn', function (d) {
                const success = parseInt(d.data.success);
                const count   = parseInt(d.data.count);
                
                swal(`Xử lý thành công : ${success.toLocaleString('vi-VN')} , từ ${count.toLocaleString('vi-VN')} dữ liệu`, {
                    icon: 'success'
                });
                
                l.stop();
            });
        });
    });    
    </script>
<?php endif; ?>