<script src="<?=config('app.view_static')?>/static/pages/scripts/visit.js?v=<?=time()?>" type="text/javascript"></script>
<div style="position: absolute; right: 25px; top: 50px;padding-right: 35px">
    <div  class="row" style="display: flex;justify-content: flex-end">
        <div class="form-group" style="display: flex; align-items: center">
            <label class="control-label" style="margin-right: 8px" >Khách hàng:</label>
            <div style="min-width: 200px">
                <select name="customer_filter_list" id="customer_filter_list" class="form-filter form-control select2" multiple style="width:100%">
                </select>
            </div>

        </div>
    </div>
</div>
