<?php if ($check ?? 1) : ?>
<div class="col-lg-2 col-md-2 col-sm-6 col-xs-12">
    <a href="<?=url($url)?>">
    <div class="dashboard-stat2 ">
        <div class="display">
            <div class="number">
                <h3 class="font-<?=$color?>">
                    <span><?=$count?></span>
                </h3>
                <small class="font-<?=$color?>"><?=$desc?></small>
            </div>
            <div class="icon">
                <i class="<?=$icon?>"></i>
            </div>
        </div>
        <div class="progress-info">
            <div class="progress">
                <span style="width: <?= $percent ?>%;" class="progress-bar progress-bar-success <?=$color?>">
                </span>
            </div>
            <div class="status">
                <div class="status-number font-<?=$color?>"> <?= $percent ?>% </div>
            </div>
        </div>
    </div>
    </a>
</div>
<?php endif; ?>
