<?php if ($check ?? 1) : ?>
<div class="col-md-2">
    <div class="widget-thumb widget-bg-color-white text-uppercase margin-bottom-20 ">
        <h4 class="widget-thumb-heading"><a href="<?=url($url)?>"><?=$desc?></a></h4>
        <div class="widget-thumb-wrap">
            <i class="widget-thumb-icon <?=$color?> fa <?=$icon?>"></i>
            <div class="widget-thumb-body">
                <span class="widget-thumb-subtitle"><?=$desc2?></span>
                <span class="widget-thumb-body-stat"><?=$count?></span>
            </div>
        </div>
    </div>
</div>
<?php endif; ?>
