<div style="float:left;margin:5px 0 5px">
    <?=icon_main_type(1)?> CH chính,
    <?=icon_is_transaction(1)?> CH có Giao dịch >= 10k,
    <?=icon_is_contract(1) . ' ' . config('title.action.pushContract')?>,
    <i class="fa fa-file-text-o" title="<?=config('info.type_contract.MKYC_HARD_COPY')?>" style="color:#d9534f"></i> <?=config('info.type_contract.MKYC_HARD_COPY')?>,
    <i class="fa fa-envelope-open" title="<?=config('info.type_contract.MKYC_IBFT')?>" style="color:#cc3300"></i> <?=config('info.type_contract.MKYC_IBFT')?>
</div>