<div name="question-group" style="border-bottom: 1px solid #eef1f5;margin-bottom: 10px">
    <input name="group_id" value="<?= $group['id'] ?>" hidden>
    <input name="group_sort" value="0" hidden>
    <div class="row">
        <div class="col-md-10">
            <div class="form-group" style="display: flex; justify-content: flex-start; align-items: center; gap: 8px">
                <label class="control-label" style="white-space: nowrap">Nhóm câu hỏi: </label>
                <select name="question_group_filed" class="form-control question_group_filed">
                    <option value="0">Chọn nhóm câu hỏi</option>
                    <?php foreach ($question_groups as $question_group) : ?>
                    <option <?= $question_group['id'] == $group['question_group_id'] ? 'selected' : '' ?>
                            value="<?= $question_group['id'] ?>">
                        <?= $question_group['name'] ?></option>
                    <?php endforeach; ?>
                </select>
                <a href="javascript:;" class="btn btn-sm btn-circle red delete-question-group" data-id="<?= $group['id'] ?>"
                <i class="fa fa-times"></i> Xóa </a>
            </div>
        </div>
        <div class="col-md-8" style="display: flex; justify-content: flex-end;align-items: center">

        </div>
    </div>
    <div style="margin-left: 40px; padding: 10px;padding-top: 0px">
        <label class="control-label">Câu hỏi và Trả lời:</label>
        <div name="question-content" class="question-content" style="padding: 10px">
            <?= $questionHtml ?>
        </div>
        <a href="javascript:;" class="btn green btn-outline add-question">
            <i class="fa fa-plus"></i> <span>Thêm câu hỏi</span>
        </a>
    </div>

</div>

