<div name="question" style="margin-top: 10px;border-bottom: 1px solid #eef1f5;padding-bottom: 8px;">
    <input name="section_question_id" value="<?= $section_question['id'] ?>" hidden>
    <input name="section_question_sort" value="<?= $section_question['sort'] ?>" hidden>
    <div class="row">
        <div class="col-md-1" style="padding: 0; display: flex; align-items: center; padding-left: 8px"
             name="question-number">
            Câu <?= $section_question['sort'] ?>
        </div>
        <div class="col-md-11">
            <div class="row">
                <div class="col-md-8">
                    <div class="form-group">
                        <select name="question_field" class="form-control question_field">
                            <option value="0">Chọn câu hỏi</option>
                            <?php foreach ($question_list as $q) : ?>
                                <option <?= $q['id'] == $question['id'] ? 'selected' : '' ?>
                                        value="<?= $q['id'] ?>">
                                    <?= $q['content'] ?></option>
                            <?php endforeach; ?>

                        </select>
                    </div>
                </div>
                <div class="col-md-4">
                    <a href="javascript:;" class="btn btn-sm btn-circle red delete-question" data-id="<?= $section_question['id'] ?>"
                    <i class="fa fa-times"></i> Xóa </a>
                </div>
            </div>
        </div>
    </div>
    <div class="row" name="question-content-detail">
        <div class="col-md-1">
        </div>
        <div class="col-md-11">
            <div class="row">
                <div class="col-md-8">
                    <textarea disabled name="question-description" class="form-control" ><?= $question['description'] ?>
                    </textarea>
                </div>
                <div class="col-md-4">
                    <div class="form-group">
                        <select name="question-type" class="form-control" disabled>
                            <option <?= $question['type'] == 1 ? 'selected' : '' ?>  value="1">Radio button</option>
                            <option <?= $question['type'] == 2 ? 'selected' : '' ?> value="2">Dropdown</option>
                            <option <?= $question['type'] == 3 ? 'selected' : '' ?> value="3">Checkbox</option>
                            <option <?= $question['type'] == 4 ? 'selected' : '' ?> value="4">Text</option>
                        </select>
                    </div>
                </div>
            </div>
            <div name="anwsers-content">
                <?php foreach ($question['anwsers'] as $ans) : ?>
                    <div class="row" name="anwser" style="margin-top: 4px">
                        <div class="col-md-8">
                            <input  type="text" value="<?= $ans['anwser'] ?>" data-id="<?= $ans['id'] ?>" name="anwser-content" class="form-control" disabled>
                        </div>
                        <div class="col-md-4">
                            <select name="section-forward" value="<?= $ans['section_forward']  ?>" data-exclude="<?= $sectionSort ?>"  class="form-control">
                                <option value="0">Chọn section đi tiếp</option>
                                <?php
                                if ($ans['section_forward'] > 0) { ?>
                                    <option selected value="<?= $ans['section_forward']  ?>">Section <?= $ans['section_forward']  ?></option>
                                <?php }  ?>
                                <option value="-1">Hoàn thành khảo sát</option>
                            </select>
                        </div>

                    </div>

                <?php endforeach; ?>
            </div>
        </div>
    </div>
</div>