<link rel="stylesheet" href="<?= config('app.view_static') ?>/static/global/bundles/datatables/datatables.min.css">
<link rel="stylesheet" href="<?= config('app.view_static') ?>/static/pages/handle-form.js?v=<?= time() ?>">
<link rel="stylesheet"
      href="<?= config('app.view_static') ?>/static/global/bundles/datatables/DataTables-1.10.16/css/dataTables.bootstrap4.min.css">
<script src="<?= config('app.view_static') ?>/static/global/bundles/datatables/datatables.min.js"></script>
<script src="<?= config('app.view_static') ?>/static/global/bundles/datatables/DataTables-1.10.16/js/dataTables.bootstrap4.min.js"></script>
<script src="<?= config('app.view_static') ?>/static/pages/handle-form.js?v=<?= time() ?>"></script>
<script src="<?= config('app.view_static') ?>/static/pages/menu/device.js?v=<?= time() ?>"></script>
<div class="main-content">
    <section class="section">
        <div class="section-body">
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-header">
                            <h4>Device</h4>
                        </div>
                        <div class="card-body">
                            <div class="table-responsive">
                                <div style="display: flex; justify-content: flex-end; margin-bottom: 10px">

                                </div>
                                <table class="table table-striped"
                                >
                                    <thead>
                                    <tr>
                                        <th style="width: 5%">
                                            #
                                        </th>
                                        <th style="width: 30%">UUID</th>
                                        <th style="width: 30%">Store Name</th>
                                        <th style="width: 15%">Status</th>
                                        <th style="width: 15%">Action</th>
                                    </tr>
                                    </thead>
                                    <tbody id="table-data">

                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </section>
    <div class="modal fade" id="modalAdd" tabindex="-1">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="formModal">Template</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">

                    <form class="" id="add-form">
                        <input name="id" hidden>
                        <div class="form-group">
                            <label>Name</label>
                            <input type="text" name="name" class="form-control">
                        </div>
                        <div class="form-group">
                            <div class="form-check">
                                <input class="form-check-input" type="checkbox" name="status" id="defaultCheck1">
                                <label class="form-check-label" for="defaultCheck1">
                                    Active
                                </label>
                            </div>
                        </div>
                        <div style="display: flex; justify-content: flex-end">
                            <button type="button"  id="btn-add" class="btn btn-primary m-t-15 waves-effect">Submit</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>