<link rel="stylesheet" href="<?= config('app.view_static') ?>/static/global/bundles/datatables/datatables.min.css">
<link rel="stylesheet" href="<?= config('app.view_static') ?>/static/global/bundles/select2/dist/css/select2.min.css">
<link rel="stylesheet"
      href="<?= config('app.view_static') ?>/static/global/bundles/datatables/DataTables-1.10.16/css/dataTables.bootstrap4.min.css">

<link rel="stylesheet" href="<?=config('app.view_static')?>/static/global/css/components.css">
<link rel="stylesheet" href="<?=config('app.view_static')?>/static/global/css/style.css">
<script src="<?= config('app.view_static') ?>/static/global/bundles/datatables/datatables.min.js"></script>
<script src="<?= config('app.view_static') ?>/static/global/bundles/datatables/DataTables-1.10.16/js/dataTables.bootstrap4.min.js"></script>
<script src="<?= config('app.view_static') ?>/static/global/bundles/select2/dist/js/select2.full.min.js"></script>
<!-- Template CSS -->
<!-- Template JS File -->
<script src="<?= config('app.view_static') ?>/static/global/js/scripts.js"></script>
<!-- Custom JS File -->
<script src="<?= config('app.view_static') ?>/static/global/js/custom.js"></script>
<script src="<?= config('app.view_static') ?>/static/pages/handle-form.js?v=<?= time() ?>"></script>
<script src="<?= config('app.view_static') ?>/static/pages/menu/store.js?v=<?= time() ?>"></script>
<style>
    .card-panel{
        border: 1px solid #e7ecf1!important;
        padding: 12px 20px 15px;
        background-color: #fff;
        box-shadow: 0 2px 3px 2px rgba(0,0,0,.03);
    }

    .panel-header{
       border-bottom:  solid 0.5px #f9f9f9;
        display: flex;
        align-items: center;
        min-height: 36px;

    }
    .panel-header .caption{
        font-weight: bold;

    }
    .panel-header .space{
        flex: 1 1 auto;

    }
    .panel-header .tools{
        float: right;

    }
    .panel-body{

    }
</style>
<div class="main-content">
    <section class="section">
        <div class="section-body">
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-header">
                            <h4>Store</h4>
                        </div>
                        <div class="card-body">
                            <div class="table-responsive">
                                <div style="display: flex; justify-content: flex-end; margin-bottom: 10px">
                                    <div class="dt-buttons btn-group">
                                        <button class="btn btn-primary" id="add"  style="width: 100px"
                                        ><span>Add</span></button>
                                    </div>
                                </div>
                                <table class="table table-striped"
                                >
                                    <thead>
                                    <tr>
                                        <th style="width: 5%">
                                            #
                                        </th>
                                        <th style="width: 10%">Name</th>
                                        <th style="width: 20%">Address</th>
                                        <th style="width: 8%">Type</th>
                                        <th style="width: 8%">Phone</th>
                                        <th style="width: 5%">Status</th>
                                        <th style="width: 10%">Action</th>
                                    </tr>
                                    </thead>
                                    <tbody id="table-data">

                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </section>
    <div class="modal fade" id="modalAdd" tabindex="-1">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="formModal">Store</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">

                    <form class="" id="add-form">
                        <input name="id" hidden>
                        <div class="form-group">
                            <label>Name</label>
                            <input type="text" name="name" class="form-control">
                        </div>
                        <div class="form-group">
                            <label>Store Type</label>
                            <select class="form-control" name="store_type">
                                <option value="0">Please select Store Type </option>
                                <?php foreach ($store_type_list as $v) : ?>
                                    <option value="<?= $v['id'] ?>"><?=$v['name'] ?></option>
                                <?php endforeach; ?>
                            </select>
                        </div>
                        <div class="form-group">
                            <label>Phone</label>
                            <input type="text" name="phone" class="form-control">
                        </div>
                        <div class="form-group">
                            <label>Wifi Pass</label>
                            <input type="text" name="wifi_pass" class="form-control">
                        </div>
                        <div class="form-group">
                            <label>Email</label>
                            <input type="text" name="email" class="form-control">
                        </div>
                        <div class="form-group">
                            <label>City</label>
                            <select class="form-control select2" name="city_id" id="city">
                                <option value="0">Please select city</option>
                                <?php foreach ($city as $v) : ?>
                                    <option value="<?= $v['id'] ?>"><?=$v['name'] ?></option>
                                <?php endforeach; ?>
                            </select>
                        </div>
                        <div class="form-group">
                            <label>District</label>
                            <select class="form-control select2" name="district_id" id="district">
                                <option value="0">Please select </option>

                            </select>
                        </div>
                        <div class="form-group">
                            <label>Ward</label>
                            <select class="form-control select2" name="ward_id" id="ward">
                                <option value="0">Please select Ward </option>

                            </select>
                        </div>
                        <div class="form-group">
                            <label>Address</label>
                            <input type="text" name="address" class="form-control">
                        </div>

                        <div class="form-group">
                            <div class="form-check">
                                <input class="form-check-input" type="checkbox" name="status" id="defaultCheck1">
                                <label class="form-check-label" for="defaultCheck1">
                                    Active
                                </label>
                            </div>
                        </div>
                        <div style="display: flex; justify-content: flex-end">
                            <button type="button"  id="btn-add" class="btn btn-primary m-t-15 waves-effect">Submit</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <div class="modal fade" id="modalMenu" tabindex="-1">
        <div class="modal-dialog modal-lg" role="document">
            <div class="modal-content">
                <div class="modal-header" style="border-bottom: solid 0.5px #f9f9f9">
                    <h5 class="modal-title" id="formModal">Menu</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <div class="card-panel">
                        <div class="panel-header">
                            <div class="caption">
                                Món Chính
                            </div>
                            <div class="space"></div>
                            <div class="tools">
                                <a data-collapse="#mycard-collapse">
                                    <i class="fas fa-minus"></i>
                                </a>
                            </div>

                        </div>
                        <div class="panel-body" id="mycard-collapse">

                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>
</div>