<link rel="stylesheet" href="<?= config('app.view_static') ?>/static/global/plugins/datatables/datatables.min.css"/>
<link rel="stylesheet"
      href="<?= config('app.view_static') ?>/static/global/plugins/datatables/plugins/bootstrap/datatables.bootstrap.css"/>
<script src="<?= config('app.view_static') ?>/static/global/plugins/datatables/datatables.min.js"
        type="text/javascript"></script>
<script src="<?= config('app.view_static') ?>/static/global/plugins/datatables/plugins/bootstrap/datatables.bootstrap.js"
        type="text/javascript"></script>
<script src="<?= config('app.view_static') ?>/static/global/scripts/hs-datatable.js" type="text/javascript"></script>
<link href="<?= config('app.view_static') ?>/static/global/plugins/bootstrap-datepicker/css/bootstrap-datepicker3.min.css"
      rel="stylesheet" type="text/css"/>
<script src="<?= config('app.view_static') ?>/static/global/plugins/bootstrap-datepicker/js/bootstrap-datepicker.js"
        type="text/javascript"></script>
<script src="<?= config('app.view_static') ?>/static/global/plugins/bootstrap-datepicker/locales/bootstrap-datepicker.vi.min.js"
        type="text/javascript"></script>
<link href="<?= config('app.view_static') ?>/static/global/plugins/select2/css/select2.min.css" rel="stylesheet"
      type="text/css"/>
<link href="<?= config('app.view_static') ?>/static/global/plugins/select2/css/select2-bootstrap.min.css"
      rel="stylesheet" type="text/css"/>
<script src="<?= config('app.view_static') ?>/static/global/plugins/select2/js/select2.full.min.js"
        type="text/javascript"></script>
<script src="https://momentjs.com/downloads/moment.js" type="text/javascript"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-sparklines/2.1.2/jquery.sparkline.min.js" type="text/javascript"></script>
<script src="<?= config('app.view_static') ?>/static/pages/scripts/load-init.js?v=<?= time() ?>"
        type="text/javascript"></script>
<script src="<?=config('app.view_static')?>/static/pages/scripts/handle-form.js?v=<?=time()?>" type="text/javascript"></script>
<script src="<?= config('app.view_static') ?>/static/pages/scripts/config/campaign.js?v=<?= time() ?>"
        type="text/javascript"></script>
<style>
    .lbl-info {
        font-weight: 600;
        margin-left: 5px;
        font-size: 20px;
    }

    .lbl-info2 {
        font-weight: 600;
        margin-left: 5px;
        font-size: 14px;
    }

    .fw400 {
        font-weight: 400 !important;
    }

    span.label {
        font-size: 14px !important
    }
</style>
<div class="page-content-wrapper">
    <div class="page-content">
        <h1 class="page-title font-dark bold uppercase"><i class="fa <?= $icon ?>"></i> <?= $title ?></h1>
        <div class="row">
            <div class="col-md-12">
                <div class="portlet light bordered">
                    <div class="portlet-body form filter">

                        <div class="form-body">
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label class="control-label">Đơn vị triển khai</label>
                                    <select name="implementation_unit_search" id="implementation_unit_search"
                                            class="form-filter form-control">
                                        <option value="0">Chọn Đơn vị triển khai</option>
                                        <?php foreach ($implementation_unit as $v) : ?>
                                            <option value="<?= $v['id'] ?>"><?= $v['name']  ?></option>
                                        <?php endforeach; ?>
                                    </select>
                                </div>
                            </div>
                        </div>
                        <div class="form-actions right">
                            <?= allow_acl('list', App\Controllers\CampaignController::class) ? block('button-search') : '' ?>
                            <?= allow_acl('update', App\Controllers\CampaignController::class) ? block('button-add') : '' ?>
                        </div>

                    </div>
                </div>
            </div>
        </div>

        <div class="modal fade" id="modalAdd" role="basic" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
                        <h4 class="modal-title" id="titleAdd">Thêm mới Campaign</h4>
                    </div>
                    <div class="modal-body">
                        <form id="add-form">
                            <input type="hidden" id="id" name="id">
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label class="control-label">Khách hàng(*)</label>
                                        <select name="customer_id" id="customer_field" class="form-control">
                                            <option value="0">Chọn Khách hàng</option>
                                            <?php foreach ($customer_list as $v) : ?>
                                                <option value="<?= $v['id'] ?>"><?=$v['customer_group'].'-'.$v['name'] ?></option>
                                            <?php endforeach; ?>
                                        </select>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label class="control-label">Đơn vị triển khai(*)</label>
                                        <select name="implementation_unit_id" id="implementation_unit_field" class="form-control">
                                            <option value="0">Chọn Đơn vị triển khai</option>
                                            <?php foreach ($implementation_unit as $v) : ?>
                                                <option value="<?= $v['id'] ?>"><?=$v['name'] ?></option>
                                            <?php endforeach; ?>
                                        </select>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label class="control-label">Tên Campaign * </label>
                                        <input type="text" class="form-control" name="name"  placeholder="Nhập tên Campaign">
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label class="control-label">Ngày bắt đầu => ngày kết thúc</label>
                                        <div class="input-daterange input-group">
                                            <input type="text" class="input-sm form-control" name="start_date" id="start_date" readonly /><span class="input-group-addon" style="border-width: 1px 1px 1px 0px;"><i class="glyphicon glyphicon-th"></i></span>
                                            <span class="input-group-addon">đến</span>
                                            <input type="text" class="input-sm form-control" name="end_date" id="end_date" readonly /><span class="input-group-addon"><i class="glyphicon glyphicon-th"></i></span>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label class="control-label fw400">Ngày nghỉ</label>
                                        <div class="input-group">
                                            <input type="text" name="leave_day" id="leave_day" class="form-control date-picker-multi text-clear-date1" readonly /><span class="input-group-addon clear-date1"><i class="glyphicon glyphicon-th"></i></span>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label class="control-label">Số ngày triển khai</label>

                                        <input type="number" name="working_day" id="working_day" class="form-control" value="0" />
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label class="control-label fw400">SL Store theo KPI</label>
                                            <input type="number" name="store_kpi_number" class="form-control" value="0"/></span>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label class="control-label">SL store đã imported</label>
                                        <input type="number" name="imported_store_number"  class="form-control" value="0" disabled />
                                    </div>
                                </div>
                            </div>
                            <fieldset style="padding:20px;border: 1px solid #c0c0c0;">
                                <legend style="border-bottom:unset;width:unset;margin-bottom:unset;">QC</legend>
                                <div class="row">
                                    <div class="col-md-12">
                                        <div class="form-group">
                                            <label class="control-label">Ngày bắt đầu => ngày kết thúc</label>
                                            <div class="input-daterange input-group">
                                                <input type="text" class="input-sm form-control" name="start_qc_date" id="start_qc_date" readonly /><span class="input-group-addon" style="border-width: 1px 1px 1px 0px;"><i class="glyphicon glyphicon-th"></i></span>
                                                <span class="input-group-addon">đến</span>
                                                <input type="text" class="input-sm form-control" name="end_qc_date" id="end_qc_date" readonly /><span class="input-group-addon"><i class="glyphicon glyphicon-th"></i></span>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label class="control-label fw400">KPI QC</label>
                                                <input type="number" name="qc_kpi_number" class="form-control" value="0"/></span>
                                        </div>
                                    </div>

                                </div>
                                <div class="row">
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label class="control-label fw400">Ngày nghỉ</label>
                                            <div class="input-group">
                                                <input type="text" name="leave_qc_day" id="leave_qc_day" class="form-control date-picker-multi text-clear-dateqc" readonly /><span class="input-group-addon clear-dateqc"><i class="glyphicon glyphicon-th"></i></span>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label class="control-label">Số ngày QC</label>
                                            <input type="number" name="working_qc_day" id="working_qc_day" class="form-control" value="0" />
                                        </div>
                                    </div>
                                </div>



                            </fieldset>
                            <div class="row" style="margin-top: 8px">
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label class="control-label">Ghi chú</label>
                                        <textarea  name="note" id="note" class="form-control" cols="8" ></textarea>
                                    </div>
                                </div>
                            </div>
                            <div class="row" style="margin-top: 8px">
                                <div class="col-md-12">
                                    <label class="mt-checkbox mt-checkbox-outline">
                                        Hoạt động: Tắt/Mở
                                        <input type="checkbox" name="status" id="status" value="1" checked>
                                        <span></span>
                                    </label>
                                </div>
                            </div>
                        </form>
                    </div>

                    <div class="modal-footer">
                        <button type="button" class="btn dark btn-outline" data-dismiss="modal">Đóng</button>
                        <button type="button" id="btn-add" class="btn green">Đồng ý</button>
                    </div>

                </div>
            </div>
        </div>

        <div class="row clearfix">
            <div class="col-md-12">
                <div class="table-container">
                    <table class="table table-striped table-bordered table-hover table-checkable"
                           id="device-table"
                           data-url="<?= url('config/campaign/list') ?>">
                        <thead>
                        <tr role="row" style="background-color: #5E738B">
                            <th width="2%" class="th-header">STT&nbsp;#</th>
                            <th width="5%" class="th-header">Chức năng</th>
                            <th width="10%" class="th-header">Khách hàng</th>
                            <th width="5%" class="th-header">ĐVTK</th>
                            <th width="12%" class="th-header">Campaign</th>
                            <th width="5%" class="th-header">SL Store theo KPI</th>
                            <th width="5%" class="th-header">SL Store Import</th>
                            <th width="5%" class="th-header">SL Store Đã Triển khai</th>
                            <th width="5%" class="th-header">KPI QC</th>
                            <th width="5%" class="th-header">SL Store Đã QC</th>
                            <th width="5%" class="th-header">SL Store Đã Nghiệm thu</th>
                            <th width="15%" class="th-header">Ngày Bắt đầu - Kết thúc Campaign</th>
                            <th width="5%" class="th-header">Trạng thái</th>
                            <th width="10%" class="th-header">Người - Ngày cập nhật</th>
                        </tr>
                        </thead>
                        <tbody>

                        </tbody>
                    </table>
                </div>
            </div>
        </div>

    </div>
</div>

