<link href="<?=config('app.view_static')?>/static/global/plugins/select2/css/select2.min.css" rel="stylesheet" type="text/css" />
<link href="<?=config('app.view_static')?>/static/global/plugins/select2/css/select2-bootstrap.min.css" rel="stylesheet" type="text/css" />
<script src="<?=config('app.view_static')?>/static/global/plugins/select2/js/select2.full.min.js" type="text/javascript"></script>
<script src="<?=config('app.view_static')?>/static/pages/scripts/load-init.js?v=<?=time()?>" type="text/javascript"></script>
<style>
    .panel .panel-title {
        font-weight: 600;
        color: blue;
    }
</style>
<div class="page-content-wrapper">
    <div class="page-content">
        <h1 class="page-title font-dark bold uppercase"><i class="fa <?= $icon ?>"></i> <?= $title ?></h1>
        <div class="modal fade" id="modalEdit" role="basic" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
                        <h4 class="modal-title" id="titleEdit"></h4>
                    </div>
                    <div class="modal-body">
                        <input type="hidden" id="id">
                        <input type="hidden" id="key">
                        <div class="row">
                            <div class="col-md-12">
                                <div class="form-group">
                                    <label class="control-label" id="lbl-name"></label>
                                    <span class="required"> * </span>
                                    <input required type="text" name="name" id="name" value="" class="form-control" placeholder="">
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-12" id="container-customer">
                                <div class="form-group">
                                    <label class="control-label" id="lbl-customer-name">Khách hàng</label>
                                    <span class="required"> * </span>
                                    <select name="customer" id="customer" class="form-control" required>
                                        <option value="">Chọn khách hàng</option>
                                    </select>
                                </div>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-md-12" id="container-group">
                                <div class="form-group">
                                    <label class="control-label" id="lbl-group-name">Nhóm</label>
                                    <span class="required"> * </span>
                                    <select name="group" id="group" class="form-control" required>
                                        <option value="">Chọn</option>
                                    </select>
                                </div>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-md-12">
                                <label class="mt-checkbox mt-checkbox-outline">
                                    Hoạt động: Tắt/Mở
                                    <input type="checkbox" id="status">
                                    <span></span>
                                </label>
                            </div>
                        </div>

                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn dark btn-outline" data-dismiss="modal">Đóng</button>
                        <button type="button" id="btn-update" class="btn green">Đồng ý</button>
                    </div>
                </div>
            </div>
        </div>

         <?php
        $html_table($customer_group, 'Nhóm Khách hàng',config('config-info.customer_group') ,'customer_group');
        $html_table($customer, 'Khách hàng',config('config-info.customer') ,'customer');
        $html_table($posm_group, ' Nhóm POSM',config('config-info.posm_group'), 'posm_group');
        $html_table($posm_error, ' Lỗi POSM',config('config-info.posm_error'), 'posm_error');
        $html_table($posm_status, 'Trạng thái Bàn giao POSM',config('config-info.posm_status'), 'posm_status');
        $html_table($posm_reason_group, 'Nhóm Lý do Không trưng bày POSM',config('config-info.posm_reason_group'), 'posm_reason_group');
         $html_table($posm_reason, 'Lý do Không trưng bày POSM',config('config-info.posm_reason'), 'posm_reason');
        $html_table($question_group, ' Nhóm Câu hỏi',config('config-info.question_group'), 'question_group');
        ?>

    </div>
</div>
<script>
    jQuery(document).ready(function () {

        $(document).on('click', '.delete', function () {
            var formData = {
                id : $(this).data('id'),
                key: $(this).data('key')
            };

            swal({
                title     : `Bạn có chắc muốn xóa ${$(this).data('title')} : ${$(this).data('name')} không ?`,
                icon      : 'warning',
                buttons   : true,
                dangerMode: true
            })
                .then((willDelete) => {
                    if (willDelete) {
                        $.ajax({
                            method  : 'POST',
                            url     : SUB_DOMAIN+'/config/info/delete',
                            dataType: 'json',
                            data    : formData,
                            success: function (response) {
                                if (response.err === 0) {
                                    swal('Xóa thành công !', {
                                        icon: 'success'
                                    });
                                    setTimeout(function () {
                                        location.reload();
                                    }, 1500);
                                } else if (response.err === -1) {
                                    swal('Xóa không thành công !', {
                                        icon: 'error'
                                    });
                                }
                            },
                            error: function (error) {
                                console.log(error);
                            }
                        });
                    }
                });
        });


        $(document).on('click', '.edit', function () {
            const title = $(this).data('title');
            const key = $(this).data('key');
            var formData = {
                id : $(this).data('id'),
                key: key
            };
            $('#key').val($(this).data('key'));
            $.ajax({
                method  : 'POST',
                url     : SUB_DOMAIN+'/config/info/get',
                dataType: 'json',
                data    : formData,
                success: function (response) {
                    if (response.err === 1) {
                        swal("Lấy thông tin không thành công !", {
                            icon: "error"
                        });
                    } else {
                        $('#titleEdit').html(`Cập nhật thông tin ${title}`);
                        $('#modalEdit').modal('show');


                        $('#lbl-name').html(title);
                        $('#lbl-name').attr('placeholder', title);
                        $('#lbl-group-name').html(`Nhóm ${title}`);



                        var data = response.data;


                        if (data.group !== undefined) {
                            var html = '<option value="0">Chọn nhóm</option>';

                            for (const d of data.group) {
                                var selected = data['group_id'] == d.id ? 'selected' : '';
                                html += `<option value="${d.id}" ${selected}>${d.name}</option>`;
                            }
                            $('#group').html(html);
                            $('#container-group').show();
                        } else {
                            $('#container-group').hide();
                        }

                        if (data.customer !== undefined) {
                            var html = '<option value="0">Chọn khách hàng</option>';

                            for (const d of data.customer) {
                                var selected = data['customer_id'] == d.id ? 'selected' : '';
                                html += `<option value="${d.id}" ${selected}>${d.name}</option>`;
                            }
                            $('#customer').html(html);
                            $('#container-customer').show();
                        } else {
                            $('#container-customer').hide();
                        }

                        $('#id').val(data.id);
                        $('#name').val(data.name);
                        $('#status').prop('checked',data.status == 1 );

                        $('#name').focus();
                    }
                },
                error: function (error) {
                    console.log(error);
                }
            });
        });

        $('#btn-update').on('click', function () {
            var formData = {
                id      : $('#id').val(),
                name    : $('#name').val(),
                status  : $('#status').is(':checked')? 1 : 0,
                group   : $('#group').val(),
                customer   : $('#customer').val(),
                key     : $('#key').val()
            };
            console.log(formData);
            $.ajax({
                data    : formData,
                dataType: 'json',
                type    : 'POST',
                url     : SUB_DOMAIN+'/config/info/update',
                success: function (resp) {
                    console.log(resp);
                    if (resp.err === 0) {
                        $('#modalEdit').modal('hide');
                        swal('Cập nhật thành công !', {
                            icon: 'success'
                        });
                        setTimeout(function () {
                            location.reload();
                        }, 1500);
                    } else if (resp.err === -1) {
                        swal(resp.msg, {
                            icon: 'warning'
                        });
                    } else {
                        swal('Xử lý thông tin không thành công !', {
                            icon: 'error'
                        });
                    }
                },
                error: function (error) {
                    console.log(error);
                }
            });
        });

        $('.add').on('click', function (e) {
            const title = $(this).data('title');
            const key = $(this).data('key');
            $('#container-group').hide();
            $('#container-customer').hide();

            $('#titleEdit').html('Thêm mới '+title);
            $('#modalEdit').modal('show');

            $('#lbl-name').html(title);
            $('#lbl-name').attr('placeholder', title);
            $('#lbl-group-name').html(`Nhóm ${title}`);



            $('#key').val(key);


            if (key !== 'customer_group') {
                var formData = {
                    key: key
                };
                $.ajax({
                    method  : 'POST',
                    url     : SUB_DOMAIN+'/config/info/get',
                    dataType: 'json',
                    data    : formData,
                    success: function (response) {
                        let data =response.data

                        if (data.group){
                            var html = '<option value="0">Chọn nhóm '+name+'</option>';
                            for (const d of data.group) {
                                html += `<option value="${d.id}">${d.name}</option>`;
                            }
                            $('#group').html(html);
                            $('#container-group').show();

                        }

                        if (data.customer){
                            $('#lbl-customer-name').html(`Khách hàng`);
                            var html = '<option value="0">Chọn khách hàng</option>';
                            for (const d of data.customer) {
                                html += `<option value="${d.id}">${d.name}</option>`;
                            }
                            $('#customer').html(html);
                            $('#container-customer').show();

                        }


                    },
                    error: function (error) {
                        console.log(error);
                    }
                });
            } else {
                $('#container-group').hide();
                $('#container-customer').hide();
            }

            $('#id').val(0);
            $('#name').val('');
            $('#name').focus();
            $('#group').val('');
            $('#customer').val('');
        });

        $('#customer').change(function () {
            let key = $('#key').val();
            if ('posm_reason' == key){
                var formData = {
                    key: key,
                    customer: $(this).val()
                };
                $.ajax({
                    method  : 'POST',
                    url     : SUB_DOMAIN+'/config/info/get',
                    dataType: 'json',
                    data    : formData,
                    success: function (response) {
                        let data =response.data

                        if (data.group){
                            var html = '<option value="0">Chọn nhóm '+name+'</option>';
                            for (const d of data.group) {
                                html += `<option value="${d.id}">${d.name}</option>`;
                            }
                            $('#group').html(html);
                            $('#container-group').show();

                        }


                    },
                    error: function (error) {
                        console.log(error);
                    }
                });
            }
        })
    });
</script>

