<link rel="stylesheet" href="<?= config('app.view_static') ?>/static/global/plugins/datatables/datatables.min.css"/>
<link rel="stylesheet"
      href="<?= config('app.view_static') ?>/static/global/plugins/datatables/plugins/bootstrap/datatables.bootstrap.css"/>
<script src="<?= config('app.view_static') ?>/static/global/plugins/datatables/datatables.min.js"
        type="text/javascript"></script>
<script src="<?= config('app.view_static') ?>/static/global/plugins/datatables/plugins/bootstrap/datatables.bootstrap.js"
        type="text/javascript"></script>
<script src="<?= config('app.view_static') ?>/static/global/scripts/hs-datatable.js" type="text/javascript"></script>
<link href="<?= config('app.view_static') ?>/static/global/plugins/bootstrap-datepicker/css/bootstrap-datepicker3.min.css"
      rel="stylesheet" type="text/css"/>
<script src="<?= config('app.view_static') ?>/static/global/plugins/bootstrap-datepicker/js/bootstrap-datepicker.js"
        type="text/javascript"></script>
<script src="<?= config('app.view_static') ?>/static/global/plugins/bootstrap-datepicker/locales/bootstrap-datepicker.vi.min.js"
        type="text/javascript"></script>
<link href="<?= config('app.view_static') ?>/static/global/plugins/select2/css/select2.min.css" rel="stylesheet"
      type="text/css"/>
<link href="<?= config('app.view_static') ?>/static/global/plugins/select2/css/select2-bootstrap.min.css"
      rel="stylesheet" type="text/css"/>
<script src="<?= config('app.view_static') ?>/static/global/plugins/select2/js/select2.full.min.js"
        type="text/javascript"></script>
<link href="<?=config('app.view_static')?>/static/global/plugins/bootstrap-fileinput/bootstrap-fileinput.css" rel="stylesheet" type="text/css" />
<script src="<?=config('app.view_static')?>/static/global/plugins/bootstrap-fileinput/bootstrap-fileinput.js" type="text/javascript"></script>
<script src="<?= config('app.view_static') ?>/static/pages/scripts/load-init.js?v=<?= time() ?>"
        type="text/javascript"></script>
<script src="<?=config('app.view_static')?>/static/pages/scripts/handle-form.js?v=<?=time()?>" type="text/javascript"></script>
<script src="<?= config('app.view_static') ?>/static/pages/scripts/config/posm-image.js?v=<?= time() ?>"
        type="text/javascript"></script>
<style>
    .lbl-info {
        font-weight: 600;
        margin-left: 5px;
        font-size: 20px;
    }

    .lbl-info2 {
        font-weight: 600;
        margin-left: 5px;
        font-size: 14px;
    }

    .fw400 {
        font-weight: 400 !important;
    }

    span.label {
        font-size: 14px !important
    }
</style>
<div class="page-content-wrapper">
    <div class="page-content">
        <h1 class="page-title font-dark bold uppercase"><i class="fa <?= $icon ?>"></i> <?= $title ?></h1>
        <div class="row">
            <div class="col-md-12">
                <div class="portlet light bordered">
                    <div class="portlet-body form filter">

                        <div class="form-body">
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label class="control-label">Đơn vị triển khai</label>
                                        <select name="implementation_unit_search" id="implementation_unit_search"
                                                class="form-filter form-control">
                                            <option value="0">Chọn Đơn vị triển khai</option>
                                            <?php foreach ($implementation_unit as $v) : ?>
                                                <option value="<?= $v['id'] ?>"><?= $v['name']  ?></option>
                                            <?php endforeach; ?>
                                        </select>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label class="control-label">Chọn POSM</label>
                                        <select name="posm_search" id="posm_search"
                                                class="form-filter form-control select2">
                                            <option value="0">Chọn POSM</option>
                                            <?php foreach ($posm as $v) : ?>
                                                <option value="<?= $v['id'] ?>"><?= sprintf('%s-%s_%s_%s', $v['customer_group'], $v['customer'], $v['posm_group'], $v['name']) ?></option>
                                            <?php endforeach; ?>
                                        </select>
                                    </div>
                                </div>

                            </div>
                        </div>
                        <div class="form-actions right">
                            <?= allow_acl('list', App\Controllers\config\ImagePosmController::class) ? block('button-search') : '' ?>
                            <?= allow_acl('update', App\Controllers\config\ImagePosmController::class) ? block('button-add') : '' ?>
                        </div>

                    </div>
                </div>
            </div>
        </div>

        <div class="modal fade" id="modalAdd" role="basic" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
                        <h4 class="modal-title" id="titleAdd">Thêm mới</h4>
                    </div>
                    <div class="modal-body">
                        <form id="add-form">
                            <input type="hidden" id="id" name="id">
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label class="control-label">Khách hàng(*)</label>
                                        <select name="customer_id" id="customer_field" class="form-control">
                                            <option value="0">Chọn Khách hàng</option>
                                            <?php foreach ($customer_list as $v) : ?>
                                                <option value="<?= $v['id'] ?>"><?=$v['customer_group'].'-'.$v['name'] ?></option>
                                            <?php endforeach; ?>
                                        </select>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label class="control-label">Đơn vị triển khai(*)</label>
                                        <select name="implementation_unit_id" id="implementation_unit_field" class="form-control">
                                            <option value="0">Chọn Đơn vị triển khai</option>
                                            <?php foreach ($implementation_unit as $v) : ?>
                                                <option value="<?= $v['id'] ?>"><?=$v['name'] ?></option>
                                            <?php endforeach; ?>
                                        </select>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label class="control-label">POSM(*)</label>
                                        <select name="posm_id" id="posm_field" class="form-control">
                                            <option value="0">Chọn POSM</option>
                                            <?php foreach ($posm as $v) : ?>
                                                <option value="<?= $v['id'] ?>"><?= sprintf('%s-%s_%s_%s', $v['customer_group'], $v['customer'], $v['posm_group'], $v['name']) ?></option>
                                            <?php endforeach; ?>
                                        </select>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-4">
                                    <div class="fileinput fileinput-new" data-provides="fileinput" name="image">
                                        <div class="fileinput-new thumbnail" style="width: 200px; height: 150px;" data-trigger="fileinput">
                                            <?php
                                            //$image = $account['image'] ? config('app.image.view_upload').$account['image'] : 'https://via.placeholder.com/200x150';
                                            $image =  'https://via.placeholder.com/200x150';
                                            ?>
                                            <img id="image" name="image" src="<?=$image?>" alt="" /> </div>
                                        <div class="fileinput-preview fileinput-exists thumbnail" style="max-width: 200px; max-height: 150px;"> </div>
                                        <div>
                                                <span class="btn default btn-file">
                                                    <span class="fileinput-new"> Chọn hình </span>
                                                    <span class="fileinput-exists"> Đổi hình </span>
                                                    <input type="file" name="image" accept="image/*"> </span>
                                            <a href="javascript:;" class="btn red fileinput-exists" name="image" data-dismiss="fileinput"> Xóa hình </a>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <div class="row">
                                <div class="col-md-12">
                                    <label class="mt-checkbox mt-checkbox-outline">
                                        Hoạt động: Tắt/Mở
                                        <input type="checkbox" name="status" id="status" value="1" checked>
                                        <span></span>
                                    </label>
                                </div>
                            </div>
                        </form>
                    </div>

                    <div class="modal-footer">
                        <button type="button" class="btn dark btn-outline" data-dismiss="modal">Đóng</button>
                        <button type="button" id="btn-add" class="btn green">Đồng ý</button>
                    </div>

                </div>
            </div>
        </div>


        <div class="row clearfix">
            <div class="col-md-12">
                <div class="table-container">
                    <table class="table table-striped table-bordered table-hover table-checkable"
                           id="device-table"
                           data-url="<?= url('config/image-posm/list') ?>">
                        <thead>
                        <tr role="row" style="background-color: #5E738B">
                            <th width="2%" class="th-header">STT&nbsp;#</th>
                            <th width="8%" class="th-header">Chức năng</th>
                            <th width="15%" class="th-header">Khách hàng</th>
                            <th width="15%" class="th-header">Đơn vị triển trai</th>
                            <th width="15%" class="th-header">POSM</th>
                            <th width="15%" class="th-header">Hình ảnh POSM</th>
                            <th width="5%" class="th-header">Trạng thái</th>
                            <th width="10%" class="th-header">Người - Ngày cập nhật</th>
                        </tr>
                        </thead>
                        <tbody></tbody>
                    </table>
                </div>
            </div>
        </div>

    </div>
</div>

