<link rel="stylesheet" href="<?=config('app.view_static')?>/static/global/plugins/datatables/datatables.min.css"/>
<link rel="stylesheet" href="<?=config('app.view_static')?>/static/global/plugins/datatables/plugins/bootstrap/datatables.bootstrap.css"/>
<script src="<?=config('app.view_static')?>/static/global/plugins/datatables/datatables.min.js" type="text/javascript"></script>
<script src="<?=config('app.view_static')?>/static/global/plugins/datatables/plugins/bootstrap/datatables.bootstrap.js" type="text/javascript"></script>
<script src="<?=config('app.view_static')?>/static/global/scripts/hs-datatable.js" type="text/javascript"></script>
<link href="<?=config('app.view_static')?>/static/global/plugins/bootstrap-switch/css/bootstrap-switch.min.css" rel="stylesheet" type="text/css" />
<script src="<?=config('app.view_static')?>/static/global/plugins/bootstrap-switch/js/bootstrap-switch.min.js" type="text/javascript"></script>
<link href="<?=config('app.view_static')?>/static/global/plugins/select2/css/select2.min.css" rel="stylesheet" type="text/css" />
<link href="<?=config('app.view_static')?>/static/global/plugins/select2/css/select2-bootstrap.min.css" rel="stylesheet" type="text/css" />
<script src="<?=config('app.view_static')?>/static/global/plugins/select2/js/select2.full.min.js" type="text/javascript"></script>
<script src="<?=config('app.view_static')?>/static/pages/scripts/load-init.js?v=<?=time()?>" type="text/javascript"></script>
<script src="<?=config('app.view_static')?>/static/pages/scripts/role-management.js?v=<?=time()?>" type="text/javascript"></script>
<div class="page-content-wrapper">
    <div class="page-content">
        <h1 class="page-title font-dark bold uppercase"><i class="fa <?= $icon ?>"></i> <?= $title ?></h1>
        <div class="row">
            <div class="col-md-12">
                <div class="portlet light bordered">
                    <div class="portlet-body form filter">
                        <div class="form-body">
                            <div class="row">
                                <div class="col-md-2">
                                    <?=block('input-text-filter', ['label'=>'Tên nhóm quyền', 'name'=>'role_search'])?>
                                </div>
                                <div class="col-md-2">
                                    <?= block('col-implementation_unit_search') ?>
                                </div>
                                <div class="col-md-2">
                                    <div class="form-group">
                                        <label class="control-label">Tỉnh thành quản lý</label>
                                        <select name="city_search" id="city_search" class="form-filter form-control select2">
                                            <option value="0">Chọn Tỉnh thành quản lý</option>
                                            <?php foreach ($city as $v) : ?>
                                            <option value="<?=$v['id']?>"><?=$v['name']?></option>
                                            <?php endforeach; ?>
                                        </select>
                                    </div>
                                </div>
                                <div class="col-md-2">
                                    <div class="form-group">
                                        <label class="control-label">Nguồn tham khảo quản lý</label>
                                        <select name="source_search" id="source_search" class="form-filter form-control">
                                            <option value="0">Chọn Nguồn tham quản lý</option>
                                            <?php foreach ($source as $v) : ?>
                                            <option value="<?=$v['id']?>"><?=$v['name']?></option>
                                            <?php endforeach; ?>
                                        </select>
                                    </div>
                                </div>
                                <div class="col-md-2">
                                    <div class="form-group">
                                        <label class="control-label">Trạng thái</label>
                                        <select name="is_active_search" id="is_active_search" class="form-filter form-control">
                                            <option value="">Chọn Trạng thái</option>
                                            <option value="1">Mở</option>
                                            <option value="0">Tắt</option>
                                        </select>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="form-actions right">
                            <?= allow_acl('list', RoleController::class) ? block('button-search') : '' ?> 
                            <?= allow_acl('update', RoleController::class) ? block('button-add') : '' ?> 
                        </div>
                        <div id="div_msg_pass" style="padding: 10px; text-align: center;" class="display-hide">
                            <span id="msg_pass" style="font-size: 20px;"></span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        
        <form role="form">
        <input type="hidden" id="id">
        <div class="modal fade" id="modalEdit" role="basic" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
                        <h4 class="modal-title" id="titleEdit"></h4>
                    </div>
                    <div class="modal-body">
                        <form class="form-horizontal" role="form">
                            <div class="row">
                                <div class="col-md-12">
                                    <?=block('input-text', ['label'=>'Tên nhóm quyền', 'name'=>'name', 'required'=>1])?>
                                </div>
                            </div>

                            <div class="row">
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label class="control-label">Mô tả</label>
                                        <textarea id="description" name="description" class="form-control" rows="5" cols="50"></textarea>
                                    </div>
                                </div>
                            </div>

                            <div class="row">
                                <div class="col-md-12">
                                    <?=block('input-switch', ['label'=>'Trạng thái', 'name'=>'is_active'])?>
                                </div>
                            </div>

                        </form>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn dark btn-outline" data-dismiss="modal">Đóng</button>
                        <button type="button" id="btn-update" class="btn green">Đồng ý</button>
                    </div>
                </div>
            </div>
        </div>
        </form>
        <div class="row clearfix">
            <div class="col-md-12">
                <div class="table-container">
                    <table class="table table-striped table-bordered table-hover table-checkable"
                           id="device-table"
                           data-url="<?=url('role/list')?>">
                        <thead>
                            <tr role="row" style="background-color: #5E738B">
                                <th class="th-header">STT&nbsp;#</th>
                                <th width="9%" class="th-header">Tên nhóm quyền</th>
                                <th width="15%" class="th-header">Mô tả</th>
                                <th width="10%" class="th-header">Đơn vị triển khai</th>
                                <th width="10%" class="th-header">Tỉnh thành quản lý</th>                            
                                <th width="10%" class="th-header">Nguồn tham khảo quản lý</th>                            
                                <th width="7%" class="th-header">Trạng thái</th>
                                <th width="9%" class="th-header">Ngày tạo</th>
                                <th width="9%" class="th-header">Người tạo</th>
                                <th width="9%" class="th-header">Ngày cập nhật</th>
                                <th width="9%" class="th-header">Người cập nhật</th>
                                <th width="15%" class="th-header">Chức năng</th>
                            </tr>
                        </thead>
                        <tbody></tbody>
                    </table>
                </div>
            </div>
        </div>

    </div>
</div>
