<!DOCTYPE html>
<html lang="en">


<!-- basic-table.html  21 Nov 2019 03:55:20 GMT -->
<head>
    <meta charset="UTF-8">
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, shrink-to-fit=no" name="viewport">
    <title>NFC Platform</title>
    <!-- General CSS Files -->
    <link rel="stylesheet" href="<?=config('app.view_static')?>/static/global/css/app.min.css">

    <!-- Template CSS -->
    <link rel="stylesheet" href="<?=config('app.view_static')?>/static/global/css/style.css">
    <link rel="stylesheet" href="<?=config('app.view_static')?>/static/global/css/components.css">
    <!-- Custom style CSS -->
    <link rel="stylesheet" href="<?=config('app.view_static')?>/static/global/css/custom.css">
    <link rel='shortcut icon' type='image/x-icon' href='<?=config('app.view_static')?>/static/global/img/favicon.ico' />
    <script src="<?=config('app.view_static')?>/static/global/bundles/jquery.min.js"></script>
    <!-- General JS Scripts -->
    <script src="<?=config('app.view_static')?>/static/global/js/app.min.js"></script>
    <!-- JS Libraies -->

</head>
<style>
    .select2{
        width: 100% !important;
        background-color: #fdfdff;
        border-color: #e4e6fc;
    }
</style>

<body>
<div class="loader"></div>
<div id="app">
    <?= $content ?>
</div>

</body>
<!-- Page Specific JS File -->
<!-- Template JS File -->
<script src="<?=config('app.view_static')?>/static/global/js/scripts.js"></script>
<!-- Custom JS File -->
<script src="<?=config('app.view_static')?>/static/global/js/custom.js"></script>

<!-- basic-table.html  21 Nov 2019 03:55:20 GMT -->
</html>