<link href="<?=config('app.view_static')?>/static/global/plugins/bootstrap-fileinput/bootstrap-fileinput.css" rel="stylesheet" type="text/css" />
<script src="<?=config('app.view_static')?>/static/global/plugins/bootstrap-fileinput/bootstrap-fileinput.js" type="text/javascript"></script>
<div class="page-content-wrapper">
    <div class="page-content">
        <h1 class="page-title font-dark bold uppercase"><?= $title ?></h1>

        <div class="row">
            <div class="col-md-12">
                <div class="portlet light bordered">
                    <div class="portlet-body form filter">
                        <form role="form" method="POST" onsubmit="return checkSubmit()" action="<?=url('profile/update')?>" enctype="multipart/form-data">
                            <div class="form-body">
                                <div class="row">
                                    <div class="col-md-2">
                                        <div class="form-group">
                                            <label class="control-label">Tên đăng nhập</label>
                                            <span><h4><b> <?= $username ?> </b></h4></span>
                                        </div>
                                    </div>                                     
                                    <div class="col-md-2">
                                        <div class="form-group">
                                            <label class="control-label">Chức danh</label>
                                            <span><h4><b> <?= $account_title ?> </b></h4></span>
                                        </div>
                                    </div>  
                                    <div class="col-md-2">
                                        <div class="form-group">
                                            <label class="control-label">Đơn vị chuyển khai</label>
                                            <span><h4><b> <?= $implementation_unit_list ?> </b></h4></span>
                                        </div>
                                    </div>
                                    <div class="col-md-2">
                                        <div class="form-group">
                                            <label class="control-label">Tỉnh thành quản lý</label>
                                            <span><h4><b> <?= $city_list ?> </b></h4></span>
                                        </div>
                                    </div>
                                    <div class="col-md-2">
                                        <div class="form-group">
                                            <label class="control-label">Nguồn tham khảo</label>
                                            <span><h4><b> <?= $source_list ?> </b></h4></span>
                                        </div>
                                    </div>
                                    <div class="col-md-2">
                                        <div class="form-group">
                                            <label class="control-label">Quyền</label>
                                            <span><h4><b> <?= $allow_role ?> </b></h4></span>
                                        </div>
                                    </div>
                                </div>    
                                <div class="row">
                                    <div class="col-md-4">
                                        <?=block('input-text', ['label'=>'Họ và tên', 'name'=>'fullname', 'required'=>1])?>
                                    </div>
                                    <div class="col-md-4">
                                        <?=block('input-text', ['label'=>'Email', 'name'=>'email', 'type'=>'email'])?>
                                    </div>
                                    <div class="col-md-4">
                                        <?=block('input-text', ['label'=>'Số điện thoại', 'name'=>'phone'])?>
                                    </div>
                                </div>                  
                                <div class="row">
                                    <div class="col-md-4">
                                        <?=block('input-text', ['label'=>'Mật khẩu cũ', 'name'=>'pass_old', 'type'=>'password'])?>
                                    </div>
                                    <div class="col-md-4">
                                        <?=block('input-text', ['label'=>'Mật khẩu mới', 'name'=>'pass', 'type'=>'password'])?>
                                    </div>
                                    <div class="col-md-4">
                                        <?=block('input-text', ['label'=>'Xác nhận mật khẩu mới', 'name'=>'repass', 'type'=>'password'])?>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-md-4">
                                        <div class="fileinput fileinput-new" data-provides="fileinput">
                                            <div class="fileinput-new thumbnail" style="width: 200px; height: 150px;">
                                                <?php
                                                $image = $account['image'] ? config('app.image.view_upload').$account['image'] : 'https://via.placeholder.com/200x150';
                                                ?>
                                                <img src="<?=$image?>" alt="" /> </div>
                                            <div class="fileinput-preview fileinput-exists thumbnail" style="max-width: 200px; max-height: 150px;"> </div>
                                            <div>
                                                <span class="btn default btn-file">
                                                    <span class="fileinput-new"> Chọn hình </span>
                                                    <span class="fileinput-exists"> Đổi hình </span>
                                                    <input type="file" name="image" accept="image/*"> </span>
                                                <a href="javascript:;" class="btn red fileinput-exists" data-dismiss="fileinput"> Xóa hình </a>
                                            </div>
                                        </div>
                                    </div>                                    
                                </div>
                                <?php if ($mess ?? 0) : ?>
                                    <div class="row">
                                        <div class="col-md-12">
                                            <div id="div_msg" align="center" class="alert alert-<?= $cls ?>">
                                                <span><?= $mess ?></span>
                                            </div>
                                        </div>
                                    </div>
                                <?php endif; ?>
                            </div>
                            <div class="form-actions right">
                                <button type="submit"  class="btn blue"><i class="fa fa-edit"></i> <span>Cập nhật thông tin</span></button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>

    </div>
</div>    
<script>
    function checkSubmit() {
        if ($('#fullname').val() === '') {
            swal('Chưa nhập họ tên', {
                icon: 'warning'
            });
            $('#fullname').focus();
            return false;
        }
//        if ($('#pass_old').val() === '') {
//            alert('Chưa nhập mật khẩu củ');
//            $('#pass_old').focus();
//            return false;
//        }
//        if ($('#pass').val() === '') {
//            alert('Chưa nhập mật khẩu mới');
//            $('#pass').focus();
//            return false;
//        }
//        if ($('#repass').val() === '') {
//            alert('Chưa nhập xác nhận mật khẩu mới');
//            $('#repass').focus();
//            return false;
//        }
        if ($('#pass').val() !== $('#repass').val()) {
            swal('Mật khẩu mới và xác nhận mật khẩu mới không khớp', {
                icon: 'warning'
            });
            $('#pass').focus();
            return false;
        }

        return true;
    }
</script>
